### ISSUE TITLE
Errors in image_inpainting_with_naive_dcgan.py

### ISSUE THREAD

**Issue by miaojiang1987** [lotuswhl/Image-inpainting-with-dcgan-pytorch#1]
Dear Author,

Thank you for writing the great software and I am trying to replicate the experiment. The first two py files were running sucessfully, however,when I ran image_inpainting_with_naive_dcgan.py and came across such issue.

RuntimeError: The size of tensor a (178) must match the size of tensor b (64) at non-singleton dimension 3
Error occurs in line 186:
 File "image_impainting_with_naive_dcgan.py", line 186, in impainting
    masked_batch_images = torch.mul(batch_images, mask).to(device)

Here is the command I ran:
 python image_impainting_with_naive_dcgan.py --cuda --output_dir ./output --netG_path ./model_result/generator_epoch_099.pth --netD_path ./model_result/discriminator_epoch_099.pth --aligned_images ./images/aligned_images/*

The predicting images are original celeba images. Could you help me figure it out?

Best,
Miao

**Comment by ningshuliang** [comment]
This is because your image size is not 64*64, it can not match the original size.

**Comment by ningshuliang** [comment]
> Dear Author,
> 
> Thank you for writing the great software and I am trying to replicate the experiment. The first two py files were running sucessfully, however,when I ran image_inpainting_with_naive_dcgan.py and came across such issue.
> 
> RuntimeError: The size of tensor a (178) must match the size of tensor b (64) at non-singleton dimension 3
> Error occurs in line 186:
> File "image_impainting_with_naive_dcgan.py", line 186, in impainting
> masked_batch_images = torch.mul(batch_images, mask).to(device)
> 
> Here is the command I ran:
> python image_impainting_with_naive_dcgan.py --cuda --output_dir ./output --netG_path ./model_result/generator_epoch_099.pth --netD_path ./model_result/discriminator_epoch_099.pth --aligned_images ./images/aligned_images/*
> 
> The predicting images are original celeba images. Could you help me figure it out?
> 
> Best,
> Miao

This is because your image size is not 64*64, it can not match the original size.
